reply_link = $('#comment-<%= @comment.id %>').find('.reply-link')
reply_link_text = reply_link.text()

if(reply_link_text == "reply" ) 
	reply_link.text("hide")
	$('#reply-form-<%= @comment.id %>')
		.addClass("comment-reply-form")
		.css("display", "block")
		.show('fast')
		.append('<%= j render "reply_form" %>')

else if(reply_link_text == "hide")
	reply_link.text("reply")
	$('#reply-form-<%= @comment.id %>')
		.removeClass("comment-reply-form")
		.empty()
		.hide('fast')
