reply_link = $('#reply-<%= @comment.id %>')
reply_link_text = reply_link.text()

if(reply_link_text == "Reply" ) 
	reply_link.text("Hide")
	$('#reply-form-<%= @comment.id %>')
		.addClass("reply-form-style")
		.css("display", "block")
		.show('fast')
		.append('<%= j render "reply_form" %>')

else if(reply_link_text == "Hide")
	reply_link.text("Reply")
	$('#reply-form-<%= @comment.id %>')
		.removeClass("reply-form-style")
		.empty()
		.hide('fast')
